### ISSUE TITLE
More tests

### ISSUE THREAD

**Issue by dphoria** [CouncilDataProject/cdp-scrapers#100]
### Feature Description

Implement unit tests for [`cdp_scrapers/legistar_content_parsers.py`](#99)

### Use Case

Test for output against known events for municipalities that host videos in web pages with content structures recognized by the functions in `legistar_content_parsers.py`.

### Solution

At least 1 test case for each function in `legistar_content_parsers.py`.

**Comment by Shak2000** [comment]
@dphoria I would be happy to do it! Could you tell me how to find example URL's in municipalities? How can I know which municipality uses LegiStar?

**Comment by dphoria** [comment]
I think most of the current list of instances, Shak. You'll have to check each instance. For example, you can see the Boston instance is just a simple `LegistarScraper`.

https://github.com/CouncilDataProject/boston/blob/main/python/cdp_boston_backend/scraper.py

The tricky part here is to find at least one instance that we can use to test one of the parsers in https://github.com/CouncilDataProject/cdp-scrapers/blob/main/cdp_scrapers/legistar_content_parsers.py . I'll try to help you find them. It'll just be some trial-and-error to see which instances hit which parsers in that legistar_content_parsers.py file.

**Comment by Shak2000** [comment]
Thanks! I will look into it.
