### ISSUE TITLE
Update static data

### ISSUE THREAD

**Issue by dphoria** [CouncilDataProject/cdp-scrapers#135]
### Describe the Bug

At minimum [portland-static.json](https://github.com/CouncilDataProject/cdp-scrapers/blob/0b1f1495b73c24e10003f9c87be7f86ce3cd715d/cdp_scrapers/instances/portland-static.json) contains outdated information.

### Expected Behavior

Static data files in `cdp_scrapers/instances` contain up-to-date information.

### Reproduction

For example, Jo Ann Hardesty is [no longer listed as a current member](https://www.portland.gov/government#toc-city-council) on the official web site for Portland, OR. Our static data file, however, has [`is_active = True`](https://github.com/CouncilDataProject/cdp-scrapers/blob/0b1f1495b73c24e10003f9c87be7f86ce3cd715d/cdp_scrapers/instances/portland-static.json#L189).

### Environment

0b1f1495b73c24e10003f9c87be7f86ce3cd715d

**Comment by evamaxfield** [comment]
Minor note, I wish we just had one person from all the cities (or a lot of the cities) that could just spend 30 minutes once a month to check the data. I might ping the Code for PDX slack channel in this case but idk. its also just plainly _asking people for work_

**Comment by Shak2000** [comment]
@dphoria @evamaxfield Can you please assign this issue to me and review my [pull request to it](https://github.com/CouncilDataProject/cdp-scrapers/pull/138).
