### ISSUE TITLE
Portland, OR scraper

### ISSUE THREAD

**Issue by dphoria** [CouncilDataProject/cdp-scrapers#43]
### Feature Description

_A clear and concise description of the feature you're requesting._

Create `portland.py` or a similarly named legislation events scraper for Portland, OR.

### Use Case

_Please provide a use case to help us understand your request in context._

The scraper will provide `ingestion_models` for `cdp-backend` when we deploy an instance for the city.

### Solution

_Please describe your ideal solution._

`PortlandScraper.get_events()` return `List[EventIngestionModel]` filled with more-than-minimal information, such as `EventMinutesItem.votes`. Because Portland, OR does not use Legistar, the scraper must obtain all the information by parsing the relevant web page(s).

### Alternatives

_Please describe any alternatives you've considered, even if you've dismissed them._

The `cdp-backend` pipeline will not work without an events scraper. There is no alternative solution.

**Comment by dphoria** [comment]
This is a board to discuss the implementation of the scraper for Portland. Let's start with minimum data, i.e.

```
Body.name
Session.session_datetime
Session.session_index
Session.video_uri
```

Then go from there.

First, a good starting point for the agenda calendar seems to be this. https://www.portland.gov/council/agenda/all

**Comment by dphoria** [comment]
The URL for an event is such that, e.g. for an event on December 8, 2021 it is https://www.portland.gov/council/agenda/2021/12/8. i.e., We can make try to open a web page given a date and if we get an error back like HTTP 404, we know there is no event on that date. If we get a valid response, we go onto parsing the event for that date.

Does this mean there is one and only one event on a given date? Or, does the URL change so that for some other `Body`, it's like https://www.portland.gov/some_committee/agenda/2021/12/8?

**Comment by dphoria** [comment]
1. Not sure what the intent is but every agenda web page lists a session dated the day following that agenda's date. [Some](https://www.portland.gov/council/agenda/2021/5/5) agendas have a valid session listed for this day-after. Most do not.  
I THINK this means that the this `EventIngestionModel.sessions`' first one would have `session_datetime = datetime(2021, 5, 5)` and the second one would have `session_datetime = datetime(2021, 5, 6)`

2. Is `EventIngestionModel.body` always `City Council`?

**Comment by Shak2000** [comment]
Hi Sung.

**Comment by dphoria** [comment]
> Hi Sung.

Hi Shak. I just thought it would be easier to discuss this here than in Slack chat. My next plan is to figure out and post a table or something similar that shows where the scraper will get what information.

e.g.
https://some/web/page.html -> `Body.name`,
https://some/other/page.html -> `Session.video_uri`

and so on.

**Comment by Shak2000** [comment]
Sounds good. What subtasks do you think I could help with?

**Comment by Shak2000** [comment]
Would you like me to help create the table that shows where the scraper will get the necessary information?

**Comment by dphoria** [comment]
Sure let's do it. We want to figure out how to get information for the following CDP models from the web pages. Not all of it, but as much as possible. `Body, EventIngestionModel, EventMinutesItem, Matter, MinutesItem, Person, Role, Session, SupportingFile, Vote`.

Descriptions for these classes are [here](https://councildataproject.org/cdp-backend/cdp_backend.pipeline.html#module-cdp_backend.pipeline.ingestion_models), and of course in the [cdp-backend repo](https://github.com/CouncilDataProject/cdp-backend) itself.

For example, we want to find out stuff like this. From a given Portland council agenda page, I think we can get `EventIngestionModel.agenda_uri` by parsing for a URL near the top that contains text like `"*agenda*pdf*"`. On some other agenda pages like [this](https://www.portland.gov/council/agenda/2021/9/29), we get the file URI by first following the "Disposition Agenda" link under "Meeting Records", then the "Download" link on that page.

Stuff like this. Any preference what you want to tackle first?

**Comment by dphoria** [comment]
We can fill this as we go: https://docs.google.com/document/d/139rNENTmHkRa3qKgOKbTdJw3GK9D_uBTqn_gracP_o0/edit?usp=sharing

**Comment by Shak2000** [comment]
Should we close this issue?

**Comment by dphoria** [comment]
I think we can. :tada:
