### ISSUE TITLE
Seattle scraper returned multi-session for single-session meeting

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-scrapers#50]
councildataproject.org/seattle-staging/#/events/c847010ce7a4

Both session 1 and session 2 have the same video and transcript. The scraper returned the same session for both sessions?? Idk if there even was a second session or not. From the end of the transcript it doesn't seem like there was a second meeting.

**Comment by dphoria** [comment]
Yes looks to be a single session meeting. When I run the scraper for 12/01, it gets the 2 meetings, both single-session meetings. So I need to figure out why apparently it ended up like that on the web site.

**Comment by dphoria** [comment]
Oh I'm running my fork. Will verify the real repo. This may be related/fixed by #49 . TBD.

**Comment by dphoria** [comment]
/test-scraper get_seattle_events --from_dt=2021-12-01T00:00:00 --to_dt=2021-12-02T00:00:00

**Comment by dphoria** [comment]
I didn't see any problems with the data from `get_events()` from the main repo either. Running a test just to be sure. But... for now looks like the data got messed up after `get_events()`.

**Comment by dphoria** [comment]
Data is correct on this test run as well. I'm lost at the moment; the data from the scraper is good... At the very least it did not get multiple sessions for this event.

**Comment by JacksonMaxfield** [comment]
I think I found the bug. It has to do with the id generator / hasher

**Comment by JacksonMaxfield** [comment]
Closing this in favor of a single cdp-backend issue
