### ISSUE TITLE
Portland Scraper Unit Tests

### ISSUE THREAD

**Issue by Shak2000** [CouncilDataProject/cdp-scrapers#54]
### Feature Description

I am adding the most basic unit tests for our scraper for Portland, OR. We will continue to add more unit tests later as we develop the scraper.

### Use Case

We will automatically test our new scrapers.

### Solution

I created unit tests for the number of events, the number of event minute items, and the video URI.

**Comment by Shak2000** [comment]
@dphoria Can you please assign this issue to me?

**Comment by JacksonMaxfield** [comment]
I got it! Thanks @Shak2000
