### ISSUE TITLE
There are two Dan Strausses (and "No sponsor" person) in Seattle-staging

### ISSUE THREAD

**Issue by tohuynh** [CouncilDataProject/cdp-scrapers#65]
### Describe the Bug

![image](https://user-images.githubusercontent.com/37560480/147782291-048206b5-dedf-4847-ad89-3e8288f498e0.png)
There are two Dan/Daniel Strauss for seattle-staging's `Person` collection.

See https://github.com/CouncilDataProject/cdp-frontend/pull/122#issuecomment-984148009 for discussion.

### Expected Behavior

Only one Dan Strauss should be in DB.

Not sure if this is a backend or scraper issue. We need to investigate what is the cause of the issue. Some possible leads:

- It is the same person just simply has two Legistar entries?
- It could also be that there was a name change in one legistar entry, but our pipeline's "primary keys" for a person think it's a new person (because of different name).
- This could also be that our Seattle static has the wrong name: https://github.com/CouncilDataProject/cdp-scrapers/blob/main/cdp_scrapers/instances/seattle-static.json#L39

cc @dphoria @JacksonMaxfield

**Comment by dphoria** [comment]
LOL for real.
