### ISSUE TITLE
Add test to pull request workflow

### ISSUE THREAD

**Issue by dphoria** [CouncilDataProject/cdp-scrapers#87]
### Feature Description

Add testing to `.github/workflows/test-and-lint.yml`. See [cdp-backend repo](https://github.com/CouncilDataProject/cdp-backend) for relevant example files - `tox.ini`, `setup.cfg`, `setup.py`, etc.

Note, we have `cdp_scrapers/tests/scraper_tests.py`.

### Use Case

Will test pull requests.

### Solution

Run tests after the `Check with Black` step in `test-and-lint.yml`.

### Alternatives

Creating a new GitHub workflow file for testing.

**Comment by Shak2000** [comment]
@dphoria @JacksonMaxfield I would like work on this issue.
